export const groupActionTypes = {
    FETCH_CHAT_START: 'FETCH_CHAT_START',
    FETCH_CHAT_SUCCESS: 'FETCH_CHAT_SUCCESS',
    FETCH_CHAT_FAILURE: 'FETCH_CHAT_FAILURE',
    UPDATE_MESSAGE_UNREAD: 'UPDATE_MESSAGE_UNREAD',
    UPDATE_SEEN_TO_TRUE: 'UPDATE_SEEN_TO_TRUE',
    UPDATE_CLOSE_COVERSATION_STATUS: 'UPDATE_CLOSE_COVERSATION_STATUS',
    UPDATE_UNREPLIED_STATUS: 'UPDATE_UNREPLIED_STATUS',
    SET_USERS: 'SET_USERS',
    UPDATE_FILTER_GROUP: 'UPDATE_FILTER_GROUP',
    UPDATE_INDIVIDUAL_CONVERSATION: 'UPDATE_INDIVIDUAL_CONVERSATION'
};

export default groupActionTypes;