const FieldActionTypes = {
  FETCH_FIELDS_START: "FETCH_FIELDS_START",
  FETCH_FIELDS_SUCCESS: "FETCH_FIELDS_SUCCESS",
  FETCH_FIELDS_FAILURE: "FETCH_FIELDS_FAILURE",
  ADD_FIELD: "ADD_FIELD",
  DELETE_FIELD: "DELETE_FIELD",
  UPDATE_FIELD: "UPDATE_FIELD",
  UPDATE_CHECKE_FIELD: "UPDATE_CHECKE_FIELD",
};

export default FieldActionTypes;
