const HomeActionTypes = {
    FETCH_MESSAGE_START: 'FETCH_MESSAGE_START',
    FETCH_MESSAGE_SUCCESS: 'FETCH_MESSAGE_SUCCESS',
    FETCH_MESSAGE_FAILURE: 'FETCH_MESSAGE_FAILURE',
    ADD_NEW_CHAT: 'ADD_NEW_CHAT',
    UPDATE_NEW_MESSAGE: 'UPDATE_NEW_MESSAGE',
    RECEIVE_NEW_CHAT: 'RECEIVE_NEW_CHAT',
    UPDATE_MESSAGE_STATUS: 'UPDATE_MESSAGE_STATUS',
};

export default HomeActionTypes;