const ContactActionTypes = {
  TOGGLE_CONTACT: "TOGGLE_CONTACT",
  FETCH_CONTACTS_START: "FETCH_CONTACTS_START",
  FETCH_CONTACTS_SUCCESS: "FETCH_CONTACTS_SUCCESS",
  FETCH_CONTACTS_FAILURE: "FETCH_CONTACTS_FAILURE",
};

export default ContactActionTypes;
