export const SMSGroupActionTypes = {
  FETCH_SMS_GROUP_FAILURE: "FETCH_SMS_GROUP_FAILURE",
  FETCH_SMS_GROUP_START: "FETCH_SMS_GROUP_START",
  FETCH_SMS_GROUP_SUCCESS: "FETCH_SMS_GROUP_SUCCESS",
  DELETE_SMS_GROUP_MEMBER: "DELETE_SMS_GROUP_MEMBER",
  ADD_SMS_GROUP_MEMBER: "ADD_SMS_GROUP_MEMBER",
};

export default SMSGroupActionTypes;
