const HomeActionTypes = {
    FETCH_LISTS_START: 'FETCH_LISTS_START',
    FETCH_LISTS_SUCCESS: 'FETCH_LISTS_SUCCESS',
    FETCH_LISTS_FAILURE: 'FETCH_LISTS_FAILURE',
};

export default HomeActionTypes;