export const DidActionTypes = {
  SEARCH_NUMBER: "SEARCH_NUMBER",
  FETCH_DID_START: "FETCH_DID_START",
  FETCH_DID_SUCCESS: "FETCH_DID_SUCCESS",
  FETCH_DID_FAILURE: "FETCH_DID_FAILURE",
};

export default DidActionTypes;
