const HomeActionTypes = {
  SET_NAV_LINK: "SET_NAV_LINK",
  TOGGLE_OPEN_SIDEBAR: "TOGGLE_OPEN_SIDEBAR",
  TOGGLE_PROFILE_HIDDEN: "TOGGLE_PROFILE_HIDDEN",
  UPDATE_CONVERSATION_MODAL: "UPDATE_CONVERSATION_MODAL",
  UPDATE_NEW_DID_MODAL: "UPDATE_NEW_DID_MODAL",
  UPDATE_NEW_Group_MODAL: "UPDATE_NEW_Group_MODAL",
  MODIFY_Group_MODAL: "MODIFY_Group_MODAL",
  MODIFY_DID_MODAL: "MODIFY_DID_MODAL",
  DELETE_DID_MODAL: "DELETE_DID_MODAL",
  DELETE_Group_MODAL: "DELETE_Group_MODAL",
  FILTER_CONVERSATION: "FILTER_CONVERSATION",
};

export default HomeActionTypes;
