export const UserActionTypes = {
   // SET_CURRENT_USER: 'SET_CURRENT_USER',
   FETCH_USER: 'FETCH_USER',
   UPDATE_USER: 'UPDATE_USER',
   FETCH_USER_START: 'FETCH_USER_START',
   FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
   FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
   UPDATE_PLAN: 'UPDATE_PLAN',
   USER_LOGOUT: 'USER_LOGOUT',
   LOCAL_REGISTER: 'LOCAL_REGISTER',
   LOCAL_LOGIN: 'LOCAL_LOGIN',
   FETCH_SAME_DOMAIN_EMAILS: 'FETCH_SAME_DOMAIN_EMAILS',
   USER_AUTH_ERROR: 'USER_AUTH_ERROR'
};

export default UserActionTypes;