export const groupActionTypes = {
  FETCH_GROUP_FAILURE: "FETCH_GROUP_FAILURE",
  FETCH_GROUP_START: "FETCH_GROUP_START",
  FETCH_GROUP_SUCCESS: "FETCH_GROUP_SUCCESS",
  DELETE_GROUP_MEMBER: "DELETE_GROUP_MEMBER",
  ADD_GROUP_MEMBER: "ADD_GROUP_MEMBER",
};

export default groupActionTypes;
